!HierarchyState
data_flows:
    4: !DataFlow {data_flow_id: 4, from_key: 2, from_state: YVNWJU, to_key: 3, to_state: FOEGDK}
    6: !DataFlow {data_flow_id: 6, from_key: 1, from_state: YVNWJU, to_key: 1, to_state: FOEGDK}
    7: !DataFlow {data_flow_id: 7, from_key: 1, from_state: YVNWJU, to_key: 2, to_state: WLYRHK}
    8: !DataFlow {data_flow_id: 8, from_key: 3, from_state: WLYRHK, to_key: 1, to_state: XMQBQM}
    9: !DataFlow {data_flow_id: 9, from_key: 2, from_state: YVNWJU, to_key: 3, to_state: XMQBQM}
    10: !DataFlow {data_flow_id: 10, from_key: 3, from_state: WLYRHK, to_key: 2, to_state: DIDVOV}
    13: !DataFlow {data_flow_id: 13, from_key: 3, from_state: DIDVOV, to_key: 12,
        to_state: YVNWJU}
filename: script.py
input_data_ports:
    1: !DataPort {data_port_id: 1, data_type: int, default_value: 10, name: number_in}
    2: !DataPort {data_port_id: 2, data_type: str, default_value: beer, name: type}
name: decimate beers
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    12: !DataPort {data_port_id: 12, data_type: int, default_value: null, name: number_out}
path: ../../test_scripts/backward_step_test/GLSUJY/OOECFM/YVNWJU
scoped_variables: {}
state_id: YVNWJU
state_type: STATE_TYPE.HIERARCHY
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: FOEGDK,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: FOEGDK, to_outcome: null, to_state: WLYRHK,
        transition_id: 2}
    3: !Transition {from_outcome: 0, from_state: WLYRHK, to_outcome: null, to_state: XMQBQM,
        transition_id: 3}
    4: !Transition {from_outcome: 0, from_state: XMQBQM, to_outcome: null, to_state: DIDVOV,
        transition_id: 4}
    6: !Transition {from_outcome: 0, from_state: DIDVOV, to_outcome: 0, to_state: null,
        transition_id: 6}
