!PreemptiveConcurrencyState
data_flows: {}
description: null
input_data_ports: {}
name: preemption_behaviour_test
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
scoped_variables: {}
state_id: FYMCWW
transitions:
    1: !Transition {from_outcome: 0, from_state: TYYIIU, to_outcome: 0, to_state: FYMCWW,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: LGQFZM, to_outcome: 0, to_state: FYMCWW,
        transition_id: 2}
