!HierarchyState
data_flows: {}
description: null
input_data_ports: {}
name: !!python/unicode '99_bottles_of_beer_in_library'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_ports: {}
scoped_variables: {}
state_id: !!python/unicode 'RZSYNB'
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: !!python/unicode 'UNBQOS',
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: !!python/unicode 'UNBQOS', to_outcome: 0,
        to_state: !!python/unicode 'RZSYNB', transition_id: 2}
