TYPE: SM_CONFIG

LIBRARY_PATHS: {"generic": "${RAFCON_LIB_PATH}/generic"}
LIBRARY_RECOVERY_MODE: False

PROFILER_RUN: False
PROFILER_VIEWER: True
PROFILER_RESULT_PATH: "/tmp/"

ENABLE_EXEC_LOG: False
EXEC_LOG_PATH: "%RAFCON_TEMP_PATH_BASE/execution_logs"
