!HierarchyState
data_flows:
    1: !DataFlow {data_flow_id: 1, from_key: 1, from_state: GXTDYN, to_key: 1, to_state: UQFDVJ}
filename: script.py
input_data_ports: {}
name: hungry turtle demo
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success1, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/hungry_turtle_demo/GXTDYN
scoped_variables:
    1: !ScopedVariable {data_type: str, default_value: hungry_turtle, name: node_name_soped_var,
        scoped_variable_id: 1}
start_state: UQFDVJ
state_id: GXTDYN
state_type: STATE_TYPE.HIERARCHY
transitions:
    1: !Transition {from_outcome: 0, from_state: UQFDVJ, to_outcome: null, to_state: LCMNPY,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: LCMNPY, to_outcome: null, to_state: AAYCDL,
        transition_id: 2}
    3: !Transition {from_outcome: 0, from_state: IDDBQS, to_outcome: null, to_state: FFFIRC,
        transition_id: 3}
    4: !Transition {from_outcome: 0, from_state: KPXIPY, to_outcome: null, to_state: IDDBQS,
        transition_id: 4}
    5: !Transition {from_outcome: 0, from_state: AAYCDL, to_outcome: null, to_state: KPXIPY,
        transition_id: 1}
    6: !Transition {from_outcome: 0, from_state: FFFIRC, to_outcome: null, to_state: KCYXIY,
        transition_id: 6}
