!HierarchyState
data_flows:
    5: !DataFlow {from_key: 1, from_state: GXTDYN, to_key: 1, to_state: UQFDVJ}
filename: script.py
input_data_ports: {}
name: hungry_turtle_demo
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success1, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/hungry_turtle_demo/GXTDYN
scoped_variables:
    1: !ScopedVariable {data_type: str, default_value: hungry_turtle, name: a_new_scoped_variable0,
        scoped_variable_id: 1}
start_state: UQFDVJ
state_id: GXTDYN
state_type: STATE_TYPE.HIERARCHY
transitions:
    2: !Transition {from_outcome: 0, from_state: UQFDVJ, to_outcome: null, to_state: LCMNPY}
