!ExecutionState
filename: script.py
input_data_ports:
    27: !DataPort {data_port_id: 27, data_type: float, default_value: 0.0, name: time}
name: wait
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/library/generic/wait/PMAZHA
state_id: PMAZHA
