!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: Turtle Position Subscriber Hierarchy State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
output_data_ports: {}
path: ../../test_scripts/basic_turtle_demo_sm/QKRZOE/BGTEQR/MESWBV
scoped_variables: {}
start_state: JGLVPV
state_id: MESWBV
state_type: STATE_TYPE.HIERARCHY
transitions:
    2: !Transition {from_outcome: 0, from_state: JGLVPV, to_outcome: null, to_state: JGLVPV}
