!ExecutionState
description: null
filename: script.py
input_data_ports: {}
name: s3
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: /home/brunner/develop/flow-control/source/test_scripts/preemption_bahaviour_test_sm/FYMCWW/LGQFZM/DDSVOQ
state_id: DDSVOQ
