!ExecutionState
description: null
input_data_ports:
    0: !InputDataPort {data_port_id: 0, data_type: &id001 !!python/name:__builtin__.int '',
        default_value: 0, name: in0}
    1: !InputDataPort {data_port_id: 1, data_type: *id001, default_value: 0, name: in1}
name: add values
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    2: !OutputDataPort {data_port_id: 2, data_type: *id001, default_value: 0, name: out}
state_id: UWRGPB
