!ExecutionState
filename: script.py
input_data_ports:
    13: !DataPort {data_port_id: 13, data_type: str, default_value: null, name: turtle
            to eat}
name: Eat
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Finished Eating, outcome_id: 0}
output_data_ports: {}
path: TIOPDF/DQYWWW/INVPZI
state_id: INVPZI
state_type: STATE_TYPE.EXECUTION
