!LibraryState
filename: script.py
input_data_ports: {}
library_name: clear_field
library_path: turtle_libraries
name: clear field
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/basic_turtle_demo_sm/CDMJPK/RMKGEW/KYENSZ/VCWTIY
state_id: VCWTIY
state_type: STATE_TYPE.LIBRARY
version: '0.1'
