!LibraryState
input_data_port_runtime_values: {}
library_name: clear_field
library_path: turtle_libraries
name: clear field
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_port_runtime_values: {}
state_id: VCWTIY
use_runtime_value_input_data_ports: {}
use_runtime_value_output_data_ports: {}
version: '0.1'
