!ExecutionState
description: null
input_data_ports:
    2: !InputDataPort {data_port_id: 2, data_type: &id001 !!python/name:__builtin__.int '',
        default_value: null, name: number}
name: Decimate Wine
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    3: !OutputDataPort {data_port_id: 3, data_type: *id001, default_value: null, name: number}
state_id: ORWCXC
