!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: Turtle Position Subscriber Hierarchy State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
output_data_ports: {}
path: GODNET/GLMYPA/IUJATT
scoped_variables: {}
start_state: BKXXWY
state_id: IUJATT
state_type: STATE_TYPE.HIERARCHY
transitions:
    3: !Transition {from_outcome: 0, from_state: BKXXWY, to_outcome: null, to_state: BKXXWY}
