!LibraryState
filename: script.py
input_data_ports:
    1: !DataPort {data_port_id: 1, data_type: str, default_value: Decide wisely, name: text}
    2: !DataPort {data_port_id: 2, data_type: str, default_value: You only have this
            one chance, name: subtext}
    3: !DataPort
        data_port_id: 3
        data_type: list
        default_value: [Blue pill, Red pill, Call Mum]
        name: options
library_name: Show dialog
library_path: generic/dialog
name: Show dialog
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: done, outcome_id: 0}
output_data_ports:
    4: !DataPort {data_port_id: 4, data_type: int, default_value: 0, name: option}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/dialog/Dialog [Info]/RYDGSS/NMFUUQ
state_id: NMFUUQ
version: '0.1'
