!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: Move Turtle Hierarchy State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success1, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/basic_turtle_demo_sm/QKRZOE/BGTEQR/JOXEQE
scoped_variables: {}
start_state: ENFCIY
state_id: JOXEQE
state_type: STATE_TYPE.HIERARCHY
transitions:
    3: !Transition {from_outcome: 0, from_state: ENFCIY, to_outcome: null, to_state: XQMBXM}
    4: !Transition {from_outcome: 0, from_state: XQMBXM, to_outcome: null, to_state: OTHELZ}
    5: !Transition {from_outcome: 0, from_state: OTHELZ, to_outcome: null, to_state: KUFHKP}
    6: !Transition {from_outcome: 0, from_state: KUFHKP, to_outcome: null, to_state: DXXYPL}
    7: !Transition {from_outcome: 0, from_state: DXXYPL, to_outcome: null, to_state: KZLSBW}
    8: !Transition {from_outcome: 0, from_state: KZLSBW, to_outcome: null, to_state: ANAVJW}
    9: !Transition {from_outcome: 0, from_state: ANAVJW, to_outcome: null, to_state: RJMSZH}
    10: !Transition {from_outcome: 0, from_state: RJMSZH, to_outcome: null, to_state: CTAVAQ}
    11: !Transition {from_outcome: 1, from_state: CTAVAQ, to_outcome: null, to_state: CTAVAQ}
    12: !Transition {from_outcome: 0, from_state: CTAVAQ, to_outcome: null, to_state: DLYQBN}
    13: !Transition {from_outcome: 0, from_state: DLYQBN, to_outcome: 0, to_state: null}
