!DeciderState
description: null
filename: script.py
input_data_ports: {}
name: Decider
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: failure, outcome_id: 1}
output_data_ports: {}
path: /home_local/brun_sb/develop/taskcontrol/source/test_scripts/barrier_concurrency_test_sm/VFNVDL/AMWCJX/unique_decider_sate_id
state_id: unique_decider_sate_id
