!DeciderState
description: null
filename: script.py
input_data_ports:
    4: !DataPort {data_port_id: 4, data_type: int, default_value: 0, name: input_0}
    5: !DataPort {data_port_id: 5, data_type: int, default_value: 0, name: input_1}
    6: !DataPort {data_port_id: 6, data_type: int, default_value: 0, name: input_2}
name: Decider
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: failure, outcome_id: 1}
output_data_ports: {}
path: ../../test_scripts/barrier_concurrency_test_sm/VFNVDL/AMWCJX/unique_decider_sate_id
state_id: unique_decider_sate_id
