!PreemptiveConcurrencyState
data_flows: {}
description: null
input_data_ports: {}
name: !!python/unicode 'Inner Action Block'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
    1: !Outcome {name: !!python/unicode 'success2', outcome_id: 1}
output_data_ports: {}
scoped_variables: {}
state_id: !!python/unicode 'DJCDHE'
transitions:
    15: !Transition {from_outcome: 0, from_state: !!python/unicode 'TXOTLO', to_outcome: 0,
        to_state: !!python/unicode 'DJCDHE', transition_id: 15}
    16: !Transition {from_outcome: 0, from_state: !!python/unicode 'TBJQYC', to_outcome: 1,
        to_state: !!python/unicode 'DJCDHE', transition_id: 16}
