!HierarchyState
data_flows:
    2: !DataFlow {data_flow_id: 2, from_key: 0, from_state: AVGUFA, to_key: 0, to_state: UWRGPB}
    3: !DataFlow {data_flow_id: 3, from_key: 0, from_state: PMYXLT, to_key: 1, to_state: UWRGPB}
    4: !DataFlow {data_flow_id: 4, from_key: 2, from_state: UWRGPB, to_key: 0, to_state: PHZXGO}
description: null
input_data_ports: {}
name: library_relocation_test
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    0: !OutputDataPort {data_port_id: 0, data_type: !!python/name:__builtin__.int '',
        default_value: 0, name: output_0}
scoped_variables: {}
state_id: PHZXGO
transitions:
    3: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: PMYXLT,
        transition_id: 3}
    4: !Transition {from_outcome: 0, from_state: PMYXLT, to_outcome: null, to_state: AVGUFA,
        transition_id: 4}
    7: !Transition {from_outcome: 0, from_state: UWRGPB, to_outcome: 0, to_state: PHZXGO,
        transition_id: 7}
    8: !Transition {from_outcome: 0, from_state: AVGUFA, to_outcome: null, to_state: UWRGPB,
        transition_id: 8}
