arch:
  - 'sled11-x86_64-gcc4.x'
  - 'osl42-x86_64'
# arch_warn_on_failure:
arch_ignore_failure:
  - 'sled11-x86-gcc4.x'

doc_dir: 'build_doc'

test:
  - eval "$(rmpm_do env --env-format embed_sh sw.common.pip2 | xargs)"
  - python setup.py -v test
