type: ''

shell: /bin/bash -c

env:
  PATH: ['/volume/software/common/packages/rmpm/latest/bin/sled11-x86-gcc4.x', '${PATH}']

doc_dir: 'docs'

env_script:
  - OWNER_NAME=$(git remote -v | grep -e "^origin\s" | sed "s/.*[:\/]\(.*\)\/.*/\1/g" | head -1)
  - REPO_NAME=$(git remote -v | grep -e "^origin\s" | sed "s/.*[:\/]\(.*\).git.*/\1/g" | head -1)
  - pkgtool --env --env-format embed_sh sw.${OWNER_NAME}.${REPO_NAME} > rmpm_env.sh
  - source rmpm_env.sh
  - 'free_display=$(python -c "import os;  print '':'' + str(max(map(lambda d: int(d[1]), os.listdir(''/tmp/.X11-unix''))+[-1])+1)")'
  - Xvfb `echo $free_display` -fp $HOME/.fonts -shmem -screen 0 1920x1200x24 & DISPLAY=$free_display
  - export DISPLAY
  - trap 'kill $(jobs -pr)' SIGINT SIGTERM EXIT

test:
  - python setup.py -v test

doc:
  - python setup.py build_sphinx
