arch:
  - 'sled11-x86_64-gcc4.x'
  - 'osl42-x86_64'
# arch_warn_on_failure:
arch_ignore_failure:
  - 'sled11-x86-gcc4.x'

doc_dir: 'build_doc'

test:
  - export PATH=${VIRTUAL_ENV}/bin:${PATH}
  - export PYTHONPATH=${PYTHONPATH}:${VIRTUAL_ENV}/lib/python2.7/site-packages
  - echo "PATH:" $PATH
  - echo "PYTHONPATH:" $PYTHONPATH
  - pip freeze
  - python setup.py test
