version: 2

formats: all
conda:
  environment: doc/conda_environment.yml
sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false
python:
  version: 3.6
  install:
    - requirements: doc/requirements.txt
  system_packages: True
