!ExecutionState
filename: script.py
input_data_ports:
    2: !DataPort {data_port_id: 2, data_type: int, default_value: null, name: bottles}
name: Decimate Bottles
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    3: !DataPort {data_port_id: 3, data_type: int, default_value: null, name: bottles}
path: ../../test_scripts/backward_step_library_test/GLSUJY/SMCOIB/OUWQUJ
state_id: OUWQUJ
state_type: STATE_TYPE.EXECUTION
