!ExecutionState
filename: script.py
input_data_ports:
    8: !DataPort {data_port_id: 8, data_type: dict, default_value: null, name: user
            turtle position}
name: Calculate position difference
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports:
    9: !DataPort {data_port_id: 9, data_type: dict, default_value: null, name: distance
            to user turtle}
path: TIOPDF/DQYWWW/JADXUB/JMVNLG/GIXGKB
state_id: GIXGKB
state_type: STATE_TYPE.EXECUTION
