!ExecutionState
filename: first_state.py
input_data_ports:
    MyFirstDataInputPort: !DataPort {data_type: str, name: MyFirstDataInputPort}
name: MyFirstState
outcomes:
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: aborted, outcome_id: 1}
    2: !Outcome {name: preempted, outcome_id: 2}
    3: !Outcome {name: MyFirstOutcome, outcome_id: 3}
output_data_ports:
    MyFirstDataOutputPort: !DataPort {data_type: float, name: MyFirstDataOutputPort}
path: ../../test_scripts
state_id: D5PQTU
state_type: STATE_TYPE.EXECUTION
