!DeciderState
description: null
filename: script.py
input_data_ports: {}
name: decider_state
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    3: !Outcome {name: FirstOutcomeDecider, outcome_id: 3}
    4: !Outcome {name: SecondOutcomeDecider, outcome_id: 4}
output_data_ports: {}
path: barrier_state_id/unique_decider_sate_id
state_id: unique_decider_sate_id
