!PreemptiveConcurrencyState
data_flows: {}
description: null
input_data_ports: {}
name: Turtle Concurrency State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
scoped_variables: {}
state_id: RMKGEW
transitions:
    3: !Transition {from_outcome: 0, from_state: KYENSZ, to_outcome: 0, to_state: RMKGEW,
        transition_id: 3}
