!ExecutionState
description: !!python/unicode 'All data exist


    Checks whether all of the given key exist in the data storage of the next higher
    library or root state.


    Parameters:

    * key: A list with names of the data


    Outcomes:

    * yes: If all keys exist

    * no: If at least one key does not exist'
input_data_ports:
    1: !InputDataPort
        data_port_id: 1
        data_type: !!python/name:__builtin__.list ''
        default_value: []
        name: !!python/unicode 'keys'
name: !!python/unicode 'all data exist'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'yes', outcome_id: 0}
    1: !Outcome {name: !!python/unicode 'no', outcome_id: 1}
output_data_ports: {}
state_id: !!python/unicode 'MTFZBT'
