!LibraryState
filename: script.py
input_data_ports:
    1: !DataPort {data_port_id: 1, data_type: str, default_value: new_ros_node, name: node_name}
library_name: init_ros_node
library_path: ros_libraries
name: init ros node
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/hungry_turtle_demo/GXTDYN/UQFDVJ
state_id: UQFDVJ
state_type: STATE_TYPE.LIBRARY
version: '0.1'
