!ExecutionState
description: null
filename: script.py
input_data_ports:
    28: !DataPort {data_port_id: 28, data_type: float, default_value: null, name: input_data_port1}
name: SecondState
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    3: !Outcome {name: FirstOutcomeState2, outcome_id: 3}
    4: !Outcome {name: SecondOutcomeState2, outcome_id: 4}
output_data_ports:
    29: !DataPort {data_port_id: 29, data_type: float, default_value: null, name: output_data_port1}
path: barrier_state_id/id_of_state_2
state_id: id_of_state_2
