!ExecutionState
filename: script.py
input_data_ports: {}
name: move_along_joint_path
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: LWR_MOVE_ALONG_JOINT_PATH
state_id: LWR_MOVE_ALONG_JOINT_PATH
state_type: STATE_TYPE.EXECUTION
