!BarrierConcurrencyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: TurtleDemo
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: TIOPDF
scoped_variables: {}
start_state: null
state_id: TIOPDF
state_type: STATE_TYPE.BARRIER_CONCURRENCY
transitions: {}
