!LibraryState
data_flows: {}
filename: script.py
input_data_ports:
    16: !DataPort {data_port_id: 16, data_type: str, default_value: new_turtle, name: turtle_name}
    17: !DataPort {data_port_id: 17, data_type: float, default_value: 5.0, name: x_pos}
    18: !DataPort {data_port_id: 18, data_type: float, default_value: 5.0, name: y_pos}
    19: !DataPort {data_port_id: 19, data_type: float, default_value: 1.0, name: phi}
library_name: move_to_position
library_path: turtle_libraries
name: move turtle to position
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: FNYQYV/LWJSRK
scoped_variables: {}
start_state: null
state_id: LWJSRK
state_type: STATE_TYPE.LIBRARY
transitions: {}
version: '0.1'
