!ExecutionState
filename: script.py
input_data_ports: {}
name: create turtle parameter
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success1, outcome_id: 0}
output_data_ports:
    2: !DataPort {data_port_id: 2, data_type: str, default_value: val, name: turtle_name}
    3: !DataPort {data_port_id: 3, data_type: float, default_value: null, name: x_pos}
    4: !DataPort {data_port_id: 4, data_type: float, default_value: null, name: y_pos}
    5: !DataPort {data_port_id: 5, data_type: float, default_value: null, name: phi}
path: ../../test_scripts/hungry_turtle_demo/GXTDYN/LCMNPY/MVMQMI
state_id: MVMQMI
state_type: STATE_TYPE.EXECUTION
