!ExecutionState
filename: script.py
input_data_ports: {}
name: clear_field
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: CLEAR_FIELD
state_id: CLEAR_FIELD
state_type: STATE_TYPE.EXECUTION
