!ExecutionState
filename: script.py
input_data_ports:
    1: !DataPort {data_port_id: 1, data_type: int, default_value: null, name: number}
    3: !DataPort {data_port_id: 3, data_type: str, default_value: val, name: type}
name: Sing
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/backward_step_test/GLSUJY/OOECFM/GOLRUX/FOEGDK
state_id: FOEGDK
state_type: STATE_TYPE.EXECUTION
