!HierarchyState
data_flows:
    14: !DataFlow {from_key: 5, from_state: JADXUB, to_key: 13, to_state: INVPZI}
filename: script.py
input_data_ports: {}
name: Follower Turtle Bot
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
path: TIOPDF/DQYWWW
scoped_variables:
    1: !ScopedVariable {data_type: str, default_value: demo_default_value, name: demo_scoped_variable,
        scoped_variable_id: 1}
start_state: RVYPWG
state_id: DQYWWW
state_type: STATE_TYPE.HIERARCHY
transitions:
    2: !Transition {from_outcome: 0, from_state: RVYPWG, to_outcome: null, to_state: JADXUB}
    9: !Transition {from_outcome: 0, from_state: INVPZI, to_outcome: 0, to_state: JADXUB}
    10: !Transition {from_outcome: 0, from_state: JADXUB, to_outcome: 0, to_state: INVPZI}
