!ExecutionState
filename: script.py
input_data_ports: {}
name: ros_goal_request_template
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: GOAL_REQUEST
state_id: GOAL_REQUEST
state_type: STATE_TYPE.EXECUTION
