!ExecutionState
filename: script.py
input_data_ports: {}
name: move_to_cartesian_pose_position_controlled
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: LWR_MOVE_TO_CARTESIAN_POSE_POSITION_CONTROLLED
state_id: LWR_MOVE_TO_CARTESIAN_POSE_POSITION_CONTROLLED
state_type: STATE_TYPE.EXECUTION
