!BarrierConcurrencyState
data_flows:
    1: !DataFlow {data_flow_id: 1, from_key: 16, from_state: OOECFM, to_key: 1, to_state: YVNWJU}
    2: !DataFlow {data_flow_id: 2, from_key: 12, from_state: YVNWJU, to_key: 19, to_state: OOECFM}
    3: !DataFlow {data_flow_id: 3, from_key: 17, from_state: OOECFM, to_key: 1, to_state: GOLRUX}
    4: !DataFlow {data_flow_id: 4, from_key: 12, from_state: GOLRUX, to_key: 20, to_state: OOECFM}
    27: !DataFlow {data_flow_id: 27, from_key: 18, from_state: OOECFM, to_key: 1,
        to_state: TTJNXL}
    28: !DataFlow {data_flow_id: 28, from_key: 12, from_state: TTJNXL, to_key: 21,
        to_state: OOECFM}
description: null
filename: script.py
input_data_ports:
    16: !DataPort {data_port_id: 16, data_type: int, default_value: 10, name: beer_number_in}
    17: !DataPort {data_port_id: 17, data_type: int, default_value: 10, name: wine_number_in}
    18: !DataPort {data_port_id: 18, data_type: int, default_value: 10, name: whiskey_number_in}
name: concurrency decimate
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    19: !DataPort {data_port_id: 19, data_type: int, default_value: null, name: beer_number_out}
    20: !DataPort {data_port_id: 20, data_type: int, default_value: null, name: wine_number_out}
    21: !DataPort {data_port_id: 21, data_type: int, default_value: null, name: whiskey_number_out}
path: ../../test_scripts/backward_step_barrier_test/GLSUJY/OOECFM
scoped_variables: {}
state_id: OOECFM
transitions:
    1: !Transition {from_outcome: 0, from_state: YVNWJU, to_outcome: null, to_state: unique_decider_sate_id,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: GOLRUX, to_outcome: null, to_state: unique_decider_sate_id,
        transition_id: 2}
    3: !Transition {from_outcome: 0, from_state: TTJNXL, to_outcome: null, to_state: unique_decider_sate_id,
        transition_id: 3}
    4: !Transition {from_outcome: 0, from_state: unique_decider_sate_id, to_outcome: 0,
        to_state: null, transition_id: 4}
