!ExecutionState
description: null
input_data_ports:
    1: !InputDataPort {data_port_id: 1, data_type: !!python/name:__builtin__.str '',
        default_value: null, name: key}
    2: !InputDataPort {data_port_id: 2, data_type: !!python/name:__builtin__.object '',
        default_value: null, name: value}
name: store data
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
state_id: ZJDRRV
