!LibraryState
input_data_port_runtime_values: {10: new_turtle, 11: 1.0, 12: 0.3}
library_name: set_velocity
library_path: turtle_libraries
name: set velocity1
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_port_runtime_values: {}
state_id: XBYUWY
use_runtime_value_input_data_ports: {10: true, 11: true, 12: true}
use_runtime_value_output_data_ports: {}
version: '0.1'
