!PreemptiveConcurrencyState
data_flows:
    6: !DataFlow {from_key: 2, from_state: DPAMHS, to_key: 5, to_state: JADXUB}
filename: script.py
input_data_ports: {}
name: Check Food and Follow
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Eat, outcome_id: 0}
output_data_ports:
    5: !DataPort {data_port_id: 5, data_type: str, default_value: null, name: target
            turtle}
path: TIOPDF/DQYWWW/JADXUB
scoped_variables: {}
start_state: null
state_id: JADXUB
state_type: STATE_TYPE.PREEMPTION_CONCURRENCY
transitions:
    5: !Transition {from_outcome: 0, from_state: DPAMHS, to_outcome: 0, to_state: null}
