TYPE: SM_CONFIG

LIBRARY_PATHS: {"generic": "../../libraries/generic",
                "test_libraries": "../../test_scripts/test_libraries",
                 "ros_libraries": "../../test_scripts/ros_libraries",
                 "turtle_libraries": "../../test_scripts/turtle_libraries"}