!HierarchyState
data_flows:
    6: !DataFlow {data_flow_id: 6, from_key: 3, from_state: RYDGSS, to_key: 4, to_state: BMACRG}
    7: !DataFlow {data_flow_id: 7, from_key: 1, from_state: RYDGSS, to_key: 1, to_state: NMFUUQ}
    8: !DataFlow {data_flow_id: 8, from_key: 2, from_state: RYDGSS, to_key: 2, to_state: NMFUUQ}
    9: !DataFlow {data_flow_id: 9, from_key: 5, from_state: BMACRG, to_key: 3, to_state: NMFUUQ}
description: null
filename: script.py
input_data_ports:
    1: !DataPort {data_port_id: 1, data_type: str, default_value: Information, name: text}
    2: !DataPort {data_port_id: 2, data_type: str, default_value: '... to be filled
            in', name: subtext}
    3: !DataPort {data_port_id: 3, data_type: str, default_value: OK, name: button
            label}
name: Dialog [Info]
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: done, outcome_id: 0}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/dialog/Dialog [Info]/RYDGSS
scoped_variables: {}
state_id: RYDGSS
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: BMACRG,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: BMACRG, to_outcome: null, to_state: NMFUUQ,
        transition_id: 2}
    3: !Transition {from_outcome: 0, from_state: NMFUUQ, to_outcome: 0, to_state: null,
        transition_id: 3}
    4: !Transition {from_outcome: -1, from_state: NMFUUQ, to_outcome: 0, to_state: null,
        transition_id: 4}
