!ExecutionState
filename: script.py
input_data_ports:
    35: !DataPort {data_port_id: 35, data_type: int, default_value: 99, name: bottles}
name: Count bottles
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: ==0, outcome_id: 0}
    1: !Outcome {name: '>0', outcome_id: 1}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/test_scripts/99 bottles of beer/GLSUJY/SFZGMH
state_id: SFZGMH
state_type: STATE_TYPE.EXECUTION
