!PreemptiveConcurrencyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: Preemption_Concurrency
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: success2, outcome_id: 1}
output_data_ports: {}
path: /home_local/dark_room/taskcontrol/source/test_scripts/simple_preemption_example/YDPJVU/OQTLKU
scoped_variables: {}
state_id: OQTLKU
transitions:
    4: !Transition {from_outcome: 0, from_state: PFDNCM, to_outcome: 1, to_state: null,
        transition_id: 4}
    5: !Transition {from_outcome: 0, from_state: OGDDXO, to_outcome: 0, to_state: null,
        transition_id: 5}
