!HierarchyState
data_flows:
    27: !DataFlow {data_flow_id: 27, from_key: 31, from_state: NDIVLD, to_key: 35,
        to_state: SFZGMH}
    28: !DataFlow {data_flow_id: 28, from_key: 31, from_state: NDIVLD, to_key: 29,
        to_state: GLSUJY}
    33: !DataFlow {data_flow_id: 33, from_key: 29, from_state: GLSUJY, to_key: 30,
        to_state: NDIVLD}
    38: !DataFlow {data_flow_id: 38, from_key: 29, from_state: GLSUJY, to_key: 37,
        to_state: PXTKIH}
filename: script.py
input_data_ports: {}
name: 99 Bottles of Beer
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: the end, outcome_id: 0}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/test_scripts/99 bottles of beer/GLSUJY
scoped_variables:
    29: !ScopedVariable {data_type: int, default_value: 99, name: bottles, scoped_variable_id: 29}
start_state: PXTKIH
state_id: GLSUJY
state_type: STATE_TYPE.HIERARCHY
transitions:
    7: !Transition {from_outcome: 0, from_state: SFZGMH, to_outcome: 0, to_state: null,
        transition_id: 7}
    8: !Transition {from_outcome: 0, from_state: PXTKIH, to_outcome: null, to_state: NDIVLD,
        transition_id: 8}
    9: !Transition {from_outcome: 1, from_state: SFZGMH, to_outcome: null, to_state: PXTKIH,
        transition_id: 9}
    10: !Transition {from_outcome: 0, from_state: NDIVLD, to_outcome: null, to_state: SFZGMH,
        transition_id: 10}
