!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: UserControlledTurtleHierarchyState
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
path: TIOPDF/OZRYUG
scoped_variables: {}
start_state: MANNGU
state_id: OZRYUG
state_type: STATE_TYPE.HIERARCHY
transitions:
    1: !Transition {from_outcome: 0, from_state: MANNGU, to_outcome: null, to_state: MANNGU}
