!ExecutionState
description: null
input_data_ports: {}
name: !!python/unicode 'Error handler 2'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
output_data_ports: {}
state_id: !!python/unicode 'PTRCQJ'
