!ExecutionState
filename: script.py
input_data_ports:
    30: !DataPort {data_port_id: 30, data_type: int, default_value: null, name: bottles}
name: Decimate bottles
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: done, outcome_id: 0}
output_data_ports:
    31: !DataPort {data_port_id: 31, data_type: int, default_value: null, name: bottles}
path: ../../test_scripts/backward_step_library_test/GLSUJY/NDIVLD
state_id: NDIVLD
state_type: STATE_TYPE.EXECUTION
