!ExecutionState
description: null
filename: script.py
input_data_ports:
    37: !DataPort {data_port_id: 37, data_type: !!python/name:__builtin__.int '',
        default_value: 99, name: bottles}
name: Sing
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: done, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/tutorials/99_bottles_of_beer/GLSUJY/PXTKIH
state_id: PXTKIH
