!HierarchyState
data_flows:
    1: !DataFlow {data_flow_id: 1, from_key: 0, from_state: !!python/unicode 'CGJJDO',
        to_key: 0, to_state: !!python/unicode 'ESGWDP'}
description: null
input_data_ports: {}
name: !!python/unicode 'libraray1_for_relocation_test'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_ports:
    0: !OutputDataPort {data_port_id: 0, data_type: !!python/name:__builtin__.int '',
        default_value: 0, name: !!python/unicode 'out'}
scoped_variables: {}
state_id: !!python/unicode 'ESGWDP'
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: !!python/unicode 'CGJJDO',
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: !!python/unicode 'CGJJDO', to_outcome: 0,
        to_state: !!python/unicode 'ESGWDP', transition_id: 2}
