!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: Move Turtle Hierarchy State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
path: GODNET/GLMYPA/AIOBOF
scoped_variables: {}
start_state: ZGEFUV
state_id: AIOBOF
state_type: STATE_TYPE.HIERARCHY
transitions:
    5: !Transition {from_outcome: 0, from_state: ZGEFUV, to_outcome: null, to_state: KSKDFL}
    6: !Transition {from_outcome: 0, from_state: KSKDFL, to_outcome: null, to_state: POGTED}
    7: !Transition {from_outcome: 0, from_state: POGTED, to_outcome: null, to_state: YWTZKU}
    8: !Transition {from_outcome: 0, from_state: YWTZKU, to_outcome: null, to_state: IQBRSH}
    9: !Transition {from_outcome: 0, from_state: IQBRSH, to_outcome: null, to_state: DNWBFM}
    10: !Transition {from_outcome: 0, from_state: DNWBFM, to_outcome: null, to_state: POXIQP}
    11: !Transition {from_outcome: 0, from_state: POXIQP, to_outcome: null, to_state: BKDMXS}
    12: !Transition {from_outcome: 0, from_state: BKDMXS, to_outcome: null, to_state: OHBPYG}
    13: !Transition {from_outcome: 1, from_state: OHBPYG, to_outcome: null, to_state: OHBPYG}
    14: !Transition {from_outcome: 0, from_state: OHBPYG, to_outcome: null, to_state: QYRBTP}
    15: !Transition {from_outcome: 0, from_state: QYRBTP, to_outcome: 0, to_state: null}
