!HierarchyState
data_flows: {}
description: null
input_data_ports: {}
name: !!python/unicode 'Activity'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
    1: !Outcome {name: !!python/unicode 'success2', outcome_id: 1}
output_data_ports: {}
scoped_variables: {}
state_id: !!python/unicode 'PXMHZU'
transitions:
    1: !Transition {from_outcome: 0, from_state: !!python/unicode 'DJCDHE', to_outcome: null,
        to_state: !!python/unicode 'MEPUNJ', transition_id: 1}
    2: !Transition {from_outcome: -2, from_state: !!python/unicode 'DJCDHE', to_outcome: null,
        to_state: !!python/unicode 'MEPUNJ', transition_id: 2}
    3: !Transition {from_outcome: 1, from_state: !!python/unicode 'DJCDHE', to_outcome: null,
        to_state: !!python/unicode 'MEPUNJ', transition_id: 3}
    4: !Transition {from_outcome: -1, from_state: !!python/unicode 'DJCDHE', to_outcome: null,
        to_state: !!python/unicode 'KUJOBK', transition_id: 4}
    6: !Transition {from_outcome: 0, from_state: !!python/unicode 'MEPUNJ', to_outcome: 0,
        to_state: !!python/unicode 'PXMHZU', transition_id: 6}
    7: !Transition {from_outcome: 1, from_state: !!python/unicode 'MEPUNJ', to_outcome: 1,
        to_state: !!python/unicode 'PXMHZU', transition_id: 7}
    8: !Transition {from_outcome: -1, from_state: !!python/unicode 'KUJOBK', to_outcome: null,
        to_state: !!python/unicode 'PTRCQJ', transition_id: 8}
    9: !Transition {from_outcome: -1, from_state: !!python/unicode 'PTRCQJ', to_outcome: null,
        to_state: !!python/unicode 'MEPUNJ', transition_id: 9}
    10: !Transition {from_outcome: -2, from_state: !!python/unicode 'MEPUNJ', to_outcome: null,
        to_state: !!python/unicode 'ZSPXQX', transition_id: 10}
    11: !Transition {from_outcome: -2, from_state: !!python/unicode 'ZSPXQX', to_outcome: -2,
        to_state: !!python/unicode 'PXMHZU', transition_id: 11}
    17: !Transition {from_outcome: -1, from_state: !!python/unicode 'MEPUNJ', to_outcome: -1,
        to_state: !!python/unicode 'PXMHZU', transition_id: 17}
    39: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: !!python/unicode 'DJCDHE',
        transition_id: 39}
