!HierarchyState
data_flows: {}
description: null
input_data_ports: {}
name: Activity
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: success2, outcome_id: 1}
output_data_ports: {}
scoped_variables: {}
state_id: PXMHZU
transitions:
    1: !Transition {from_outcome: 0, from_state: DJCDHE, to_outcome: null, to_state: MEPUNJ,
        transition_id: 1}
    2: !Transition {from_outcome: -2, from_state: DJCDHE, to_outcome: null, to_state: MEPUNJ,
        transition_id: 2}
    3: !Transition {from_outcome: 1, from_state: DJCDHE, to_outcome: null, to_state: MEPUNJ,
        transition_id: 3}
    4: !Transition {from_outcome: -1, from_state: DJCDHE, to_outcome: null, to_state: KUJOBK,
        transition_id: 4}
    6: !Transition {from_outcome: 0, from_state: MEPUNJ, to_outcome: 0, to_state: PXMHZU,
        transition_id: 6}
    7: !Transition {from_outcome: 1, from_state: MEPUNJ, to_outcome: 1, to_state: PXMHZU,
        transition_id: 7}
    8: !Transition {from_outcome: -1, from_state: KUJOBK, to_outcome: null, to_state: PTRCQJ,
        transition_id: 8}
    9: !Transition {from_outcome: -1, from_state: PTRCQJ, to_outcome: null, to_state: MEPUNJ,
        transition_id: 9}
    10: !Transition {from_outcome: -2, from_state: MEPUNJ, to_outcome: null, to_state: ZSPXQX,
        transition_id: 10}
    11: !Transition {from_outcome: -2, from_state: ZSPXQX, to_outcome: -2, to_state: PXMHZU,
        transition_id: 11}
    17: !Transition {from_outcome: -1, from_state: MEPUNJ, to_outcome: -1, to_state: PXMHZU,
        transition_id: 17}
    39: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: DJCDHE,
        transition_id: 39}
