TYPE: NETWORK_CONFIG

SERVER_IP: 127.0.0.1
SERVER_TCP_PORT: 8888
SERVER_UDP_PORT: 9999
SERVER_HTML_PORT: 8889

CLIENT_UDP_PORT: 7777
NUMBER_UDP_MESSAGES_SENT: 10
NUMBER_UDP_MESSAGES_HISTORY: 100

NUMBER_OF_UDP_PACKAGES_UNTIL_TIMEOUT: 15
SECONDS_BETWEEN_UDP_RESEND: 2

SPACEBOT_CUP_MODE: False
AUTOCONNECT_UDP_TO_SERVER: False
AUTOCONNECT_TCP_TO_SERVER: False