!ExecutionState
description: 'Wait infinitely


    This library waits infinitely. If a preemption request occurs, the library preempts
    immediately.'
filename: script.py
input_data_ports: {}
name: wait infitinetly
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: end, outcome_id: 0}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/wait infinitely/EQVJBF
state_id: EQVJBF
