!ExecutionState
description: 'Wait a given time


    The library uses preemptive_wait to wait for the given time. If a preemption request
    occurs during the wait, the library preempts immediately.


    Parameter:

    time: Time to wait [sec]'
filename: script.py
input_data_ports:
    27: !DataPort {data_port_id: 27, data_type: float, default_value: 0.0, name: time}
name: wait
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: end, outcome_id: 0}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/wait/PMAZHA
state_id: PMAZHA
