name: rafcon
channels:
  - conda-forge
dependencies:
  - python=3.*
  - cairo=1.10
  - pygobject=3.20
  - pip:
    - pylint=1.6
    - pyyaml=3.10
    - psutil
    - jsonconversion=0.2
    - yaml_configuration=0.1
    - python-gtkmvc3-dlr=1.0
    - gaphas=1.0
