name: rafcon
channels:
  - conda-forge
  - zegami
dependencies:
  - pygobject
  - gtk
  - pip:
    - psutil==5.*
    - pylint
    - PyYAML==3.13
    - git+https://github.com/gaphor/gaphas.git@1.0.0#egg=gaphas
    - git+https://github.com/DLR-RM/python-jsonconversion.git@0.2.10#egg=python-jsonconversion
    - git+https://github.com/DLR-RM/gtkmvc3.git@gtkmvc3_1.0.0#egg=gtkmvc3
