!HierarchyState
data_flows: {}
description: null
input_data_ports: {}
name: Exit handler 2
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
scoped_variables: {}
state_id: ZSPXQX
transitions:
    12: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: BUPEID,
        transition_id: 12}
    14: !Transition {from_outcome: 0, from_state: BUPEID, to_outcome: 0, to_state: ZSPXQX,
        transition_id: 14}
