!LibraryState
data_flows: {}
filename: script.py
input_data_ports: {}
library_name: clear_field
library_path: turtle_libraries
name: clear field
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/basic_turtle_demo_sm/QKRZOE/BGTEQR/JOXEQE/DXXYPL
scoped_variables: {}
start_state: null
state_id: DXXYPL
state_type: STATE_TYPE.LIBRARY
transitions: {}
version: '0.1'
