!HierarchyState
data_flows: {}
description: null
filename: script.py
input_data_ports: {}
name: Test None SM
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: fail, outcome_id: 1}
output_data_ports: {}
path: ../../test_scripts/return_none_test_sm/VZVYGX
scoped_variables: {}
state_id: VZVYGX
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: ORZCVQ,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: ORZCVQ, to_outcome: 1, to_state: null,
        transition_id: 2}
    3: !Transition {from_outcome: -1, from_state: ORZCVQ, to_outcome: null, to_state: PRUDIX,
        transition_id: 3}
    4: !Transition {from_outcome: 0, from_state: PRUDIX, to_outcome: 0, to_state: null,
        transition_id: 4}
