!ExecutionState
filename: script.py
input_data_ports:
    10: !DataPort {data_port_id: 10, data_type: str, default_value: new_turtle, name: turtle_name}
    11: !DataPort {data_port_id: 11, data_type: float, default_value: 1.0, name: x_dir}
    12: !DataPort {data_port_id: 12, data_type: float, default_value: 0.0, name: y_dir}
    13: !DataPort {data_port_id: 13, data_type: float, default_value: 0.3, name: phi_dir}
name: move_turtle
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: SET_VELOCITY
state_id: SET_VELOCITY
state_type: STATE_TYPE.EXECUTION
