!ExecutionState
description: null
filename: script.py
input_data_ports:
    10: !DataPort {data_port_id: 10, data_type: str, default_value: new_turtle, name: turtle_name}
    11: !DataPort {data_port_id: 11, data_type: float, default_value: 1.0, name: x_vel}
    12: !DataPort {data_port_id: 12, data_type: float, default_value: 0.3, name: phi_vel}
name: move_turtle
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: /home_local/brun_sb/develop/taskcontrol/source/test_scripts/turtle_libraries/set_velocity/SET_VELOCITY
state_id: SET_VELOCITY
