!PreemptiveConcurrencyState
data_flows: {}
description: null
input_data_ports: {}
name: Outer Action Block
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: success2, outcome_id: 1}
    2: !Outcome {name: success3, outcome_id: 2}
    3: !Outcome {name: success4, outcome_id: 3}
output_data_ports: {}
scoped_variables: {}
state_id: PTLNJT
transitions:
    21: !Transition {from_outcome: 0, from_state: NAJQGQ, to_outcome: 3, to_state: PTLNJT,
        transition_id: 21}
    22: !Transition {from_outcome: 0, from_state: IONVZR, to_outcome: 2, to_state: PTLNJT,
        transition_id: 22}
    23: !Transition {from_outcome: 1, from_state: PXMHZU, to_outcome: 1, to_state: PTLNJT,
        transition_id: 23}
    24: !Transition {from_outcome: 0, from_state: PXMHZU, to_outcome: 0, to_state: PTLNJT,
        transition_id: 24}
