!PreemptiveConcurrencyState
data_flows: {}
description: null
input_data_ports: {}
name: !!python/unicode 'Outer Action Block'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
    1: !Outcome {name: !!python/unicode 'success2', outcome_id: 1}
    2: !Outcome {name: !!python/unicode 'success3', outcome_id: 2}
    3: !Outcome {name: !!python/unicode 'success4', outcome_id: 3}
output_data_ports: {}
scoped_variables: {}
state_id: !!python/unicode 'PTLNJT'
transitions:
    21: !Transition {from_outcome: 0, from_state: !!python/unicode 'NAJQGQ', to_outcome: 3,
        to_state: !!python/unicode 'PTLNJT', transition_id: 21}
    22: !Transition {from_outcome: 0, from_state: !!python/unicode 'IONVZR', to_outcome: 2,
        to_state: !!python/unicode 'PTLNJT', transition_id: 22}
    23: !Transition {from_outcome: 1, from_state: !!python/unicode 'PXMHZU', to_outcome: 1,
        to_state: !!python/unicode 'PTLNJT', transition_id: 23}
    24: !Transition {from_outcome: 0, from_state: !!python/unicode 'PXMHZU', to_outcome: 0,
        to_state: !!python/unicode 'PTLNJT', transition_id: 24}
