!LibraryState
input_data_port_runtime_values: {}
library_name: library2_for_relocation_test
library_path: test_scripts/test_libraries
name: library2_for_relocation_test
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_port_runtime_values: {0: 0}
state_id: DZWZFB
use_runtime_value_input_data_ports: {}
use_runtime_value_output_data_ports: {0: true}
version: '0.1'
