!ExecutionState
filename: script.py
input_data_ports: {}
name: Check for food
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
    1: !Outcome {name: Nothing found, outcome_id: 1}
output_data_ports:
    3: !DataPort {data_port_id: 3, data_type: str, default_value: default_turtle_value,
        name: target turtle}
path: TIOPDF/DQYWWW/JADXUB/DPAMHS/AGNUHU
state_id: AGNUHU
state_type: STATE_TYPE.EXECUTION
