!ExecutionState
description: null
filename: script.py
input_data_ports:
    3: !DataPort {data_port_id: 3, data_type: str, default_value: null, name: key}
name: load data
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    4: !DataPort {data_port_id: 4, data_type: object, default_value: null, name: value}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/libraries/load data/XTJARF
state_id: XTJARF
