!ExecutionState
description: null
input_data_ports:
    3: !InputDataPort {data_port_id: 3, data_type: !!python/name:__builtin__.str '',
        default_value: null, name: !!python/unicode 'key'}
name: !!python/unicode 'load data'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_ports:
    4: !OutputDataPort {data_port_id: 4, data_type: !!python/name:__builtin__.object '',
        default_value: null, name: !!python/unicode 'value'}
state_id: !!python/unicode 'XTJARF'
