!ExecutionState
description: null
input_data_ports:
    7: !InputDataPort {data_port_id: 7, data_type: &id001 !!python/name:__builtin__.float '',
        default_value: null, name: input0}
    8: !InputDataPort {data_port_id: 8, data_type: *id001, default_value: null, name: input1}
    9: !InputDataPort {data_port_id: 9, data_type: *id001, default_value: null, name: input2}
    10: !InputDataPort {data_port_id: 10, data_type: *id001, default_value: null,
        name: input3}
    11: !InputDataPort {data_port_id: 11, data_type: *id001, default_value: null,
        name: input4}
name: Adder
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    12: !OutputDataPort {data_port_id: 12, data_type: *id001, default_value: null,
        name: output0}
state_id: ZVLGWY
