!ExecutionState
filename: script.py
input_data_ports: {}
name: execution abortion handling
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/error_propagation_test/BNXYRR/CLRZWT/MWHPPQ
state_id: MWHPPQ
