!ExecutionState
filename: script.py
input_data_ports: {}
name: Wait1
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
path: GODNET/GLMYPA/AIOBOF/KSKDFL
state_id: KSKDFL
state_type: STATE_TYPE.EXECUTION
