!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: Turtle Position Subscriber Hierarchy State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
output_data_ports: {}
path: ../../test_scripts/tutorials/basic_turtle_demo_sm/CDMJPK/RMKGEW/WQKFUS
scoped_variables: {}
state_id: WQKFUS
transitions:
    2: !Transition {from_outcome: 0, from_state: UVLRTI, to_outcome: null, to_state: UVLRTI,
        transition_id: 2}
    3: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: UVLRTI,
        transition_id: 3}
