!ExecutionState
description: null
input_data_ports:
    3: !InputDataPort {data_port_id: 3, data_type: &id001 !!python/name:__builtin__.float '',
        default_value: null, name: data_input_port1}
name: library_execution_state2
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    4: !OutputDataPort {data_port_id: 4, data_type: *id001, default_value: null, name: data_output_port1}
state_id: IFWPMR
