!ExecutionState
filename: script.py
input_data_ports: {}
name: faulty execution state
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: /home_local/brun_sb/develop/taskcontrol/source/test_scripts/error_propagation_test/BNXYRR/CLRZWT/UOLRHV
state_id: UOLRHV
state_type: STATE_TYPE.EXECUTION
