!DeciderState
description: null
filename: script.py
input_data_ports: {}
name: Decider
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/backward_step_barrier_test/GLSUJY/OOECFM/unique_decider_sate_id
state_id: unique_decider_sate_id
