!ExecutionState
filename: script.py
input_data_ports:
    37: !DataPort {data_port_id: 37, data_type: int, default_value: 99, name: bottles}
name: Sing
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: done, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/backward_step_hierarchy_test/GLSUJY/PXTKIH
state_id: PXTKIH
state_type: STATE_TYPE.EXECUTION
