!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: Move Turtle Hierarchy State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/basic_turtle_demo_sm/CDMJPK/RMKGEW/KYENSZ
scoped_variables: {}
start_state: PAYECU
state_id: KYENSZ
state_type: STATE_TYPE.HIERARCHY
transitions:
    5: !Transition {from_outcome: 0, from_state: PAYECU, to_outcome: null, to_state: UEPNNW}
    6: !Transition {from_outcome: 0, from_state: UEPNNW, to_outcome: null, to_state: KQDJYS}
    7: !Transition {from_outcome: 0, from_state: KQDJYS, to_outcome: null, to_state: FGIXTU}
    8: !Transition {from_outcome: 0, from_state: FGIXTU, to_outcome: null, to_state: VCWTIY}
    9: !Transition {from_outcome: 0, from_state: VCWTIY, to_outcome: null, to_state: WYYCKU}
    10: !Transition {from_outcome: 0, from_state: WYYCKU, to_outcome: null, to_state: XBYUWY}
    11: !Transition {from_outcome: 0, from_state: XBYUWY, to_outcome: null, to_state: RQXPAI}
    12: !Transition {from_outcome: 0, from_state: RQXPAI, to_outcome: null, to_state: MCOLIQ}
    13: !Transition {from_outcome: 1, from_state: MCOLIQ, to_outcome: null, to_state: MCOLIQ}
    14: !Transition {from_outcome: 0, from_state: MCOLIQ, to_outcome: null, to_state: HRARIS}
    15: !Transition {from_outcome: 0, from_state: HRARIS, to_outcome: 0, to_state: null}
