!HierarchyState
data_flows:
    6: !DataFlow {data_flow_id: 6, from_key: 4, from_state: LEUWGC, to_key: 5, to_state: GTDDSU}
    7: !DataFlow {data_flow_id: 7, from_key: 4, from_state: LEUWGC, to_key: 1, to_state: OTNPAN}
    8: !DataFlow {data_flow_id: 8, from_key: 1, from_state: OTNPAN, to_key: 3, to_state: LEUWGC}
    9: !DataFlow {data_flow_id: 9, from_key: 1, from_state: OTNPAN, to_key: 2, to_state: GGROCS}
description: null
input_data_ports: {}
name: 99 Little Bugs
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
scoped_variables:
    1: !ScopedVariable {data_port_id: 1, data_type: !!python/name:__builtin__.int '',
        default_value: 99, name: Bugs}
state_id: OTNPAN
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: GGROCS,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: GGROCS, to_outcome: null, to_state: LEUWGC,
        transition_id: 2}
    3: !Transition {from_outcome: 0, from_state: LEUWGC, to_outcome: null, to_state: GTDDSU,
        transition_id: 3}
    4: !Transition {from_outcome: 1, from_state: GTDDSU, to_outcome: 0, to_state: OTNPAN,
        transition_id: 4}
    5: !Transition {from_outcome: 0, from_state: GTDDSU, to_outcome: null, to_state: GGROCS,
        transition_id: 5}
