!ExecutionState
filename: script.py
input_data_ports:
    15: !DataPort {data_port_id: 15, data_type: str, default_value: new_turtle, name: turtle_name}
name: turtle_position_subscriber
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: TURTLE_POSITION_SUBSCRIBER
state_id: TURTLE_POSITION_SUBSCRIBER
state_type: STATE_TYPE.EXECUTION
