!ExecutionState
description: null
filename: script.py
input_data_ports:
    13: !DataPort {data_port_id: 13, data_type: int, default_value: 0, name: option}
name: Decider
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: option 1, outcome_id: 0}
    1: !Outcome {name: option 2, outcome_id: 1}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/dialog/Dialog [2 options]/AQRXOD/RFMJKJ
state_id: RFMJKJ
