!BarrierConcurrencyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: Turtle Concurrency State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success1, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/basic_turtle_demo_sm/XBMYHQ/XYEQEX
scoped_variables: {}
start_state: null
state_id: XYEQEX
state_type: STATE_TYPE.BARRIER_CONCURRENCY
transitions:
    27: !Transition {from_outcome: 0, from_state: KSWUOO, to_outcome: 0, to_state: null}
