!HierarchyState
data_flows:
    6: !DataFlow {from_key: 2, from_state: MVMQMI, to_key: 2, to_state: KDRRRW}
    7: !DataFlow {from_key: 3, from_state: MVMQMI, to_key: 3, to_state: KDRRRW}
    8: !DataFlow {from_key: 4, from_state: MVMQMI, to_key: 4, to_state: KDRRRW}
    9: !DataFlow {from_key: 5, from_state: MVMQMI, to_key: 5, to_state: KDRRRW}
filename: script.py
input_data_ports: {}
name: create food
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
output_data_ports: {}
path: ../../test_scripts/hungry_turtle_demo/GXTDYN/LCMNPY
scoped_variables: {}
start_state: MVMQMI
state_id: LCMNPY
state_type: STATE_TYPE.HIERARCHY
transitions:
    3: !Transition {from_outcome: 0, from_state: MVMQMI, to_outcome: null, to_state: KDRRRW}
