!LibraryState
filename: script.py
input_data_ports:
    1: !DataPort {data_port_id: 1, data_type: int, default_value: 200, name: bottles_input}
library_name: backward_99_bottles_of_beer
library_path: test_libraries
name: 99 bottles library state
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: the end, outcome_id: 0}
output_data_ports:
    2: !DataPort {data_port_id: 2, data_type: int, default_value: 0, name: bottles_output}
path: ../../test_scripts/backward_step_library_test/GLSUJY/XHDWFR
state_id: XHDWFR
state_type: STATE_TYPE.LIBRARY
version: '0.1'
