!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: BasicTurtleDemo
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/basic_turtle_demo_sm/CDMJPK
scoped_variables: {}
state_id: CDMJPK
state_type: STATE_TYPE.HIERARCHY
transitions:
    1: !Transition {from_outcome: 0, from_state: CKIWDE, to_outcome: null, to_state: RMKGEW,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: RMKGEW, to_outcome: 0, to_state: null,
        transition_id: 2}
    3: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: CKIWDE,
        transition_id: 3}
