!LibraryState
input_data_port_runtime_values: {}
library_name: !!python/unicode '99_bottles_of_beer'
library_path: !!python/unicode 'tutorials'
name: !!python/unicode '99_bottles_of_beer'
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: the end, outcome_id: 0}
output_data_port_runtime_values: {}
state_id: !!python/unicode 'UNBQOS'
use_runtime_value_input_data_ports: {}
use_runtime_value_output_data_ports: {}
version: !!python/unicode '0.1'
