!HierarchyState
data_flows: {}
filename: script.py
input_data_ports: {}
name: faulty hierarchy
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: /home_local/brun_sb/develop/taskcontrol/source/test_scripts/error_propagation_test/BNXYRR/CLRZWT
scoped_variables: {}
state_id: CLRZWT
state_type: STATE_TYPE.HIERARCHY
transitions:
    3: !Transition {from_outcome: -1, from_state: UOLRHV, to_outcome: null, to_state: MWHPPQ,
        transition_id: 3}
    4: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: UOLRHV,
        transition_id: 4}
    5: !Transition {from_outcome: 0, from_state: MWHPPQ, to_outcome: 0, to_state: null,
        transition_id: 5}
