!HierarchyState
data_flows:
    3: !DataFlow {data_flow_id: 3, from_key: 1, from_state: !!python/unicode 'GLSUJY',
        to_key: 29, to_state: !!python/unicode 'GLSUJY'}
    4: !DataFlow {data_flow_id: 4, from_key: 29, from_state: !!python/unicode 'GLSUJY',
        to_key: 2, to_state: !!python/unicode 'GLSUJY'}
    9: !DataFlow {data_flow_id: 9, from_key: 8, from_state: !!python/unicode 'SMCOIB',
        to_key: 29, to_state: !!python/unicode 'GLSUJY'}
    10: !DataFlow {data_flow_id: 10, from_key: 31, from_state: !!python/unicode 'NDIVLD',
        to_key: 2, to_state: !!python/unicode 'SMCOIB'}
    27: !DataFlow {data_flow_id: 27, from_key: 31, from_state: !!python/unicode 'NDIVLD',
        to_key: 35, to_state: !!python/unicode 'SFZGMH'}
    28: !DataFlow {data_flow_id: 28, from_key: 31, from_state: !!python/unicode 'NDIVLD',
        to_key: 29, to_state: !!python/unicode 'GLSUJY'}
    33: !DataFlow {data_flow_id: 33, from_key: 29, from_state: !!python/unicode 'GLSUJY',
        to_key: 30, to_state: !!python/unicode 'NDIVLD'}
    38: !DataFlow {data_flow_id: 38, from_key: 29, from_state: !!python/unicode 'GLSUJY',
        to_key: 37, to_state: !!python/unicode 'PXTKIH'}
description: null
input_data_ports:
    1: !InputDataPort {data_port_id: 1, data_type: &id001 !!python/name:__builtin__.int '',
        default_value: 99, name: !!python/unicode 'bottles_input'}
name: !!python/unicode 'stepping_test'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'the end', outcome_id: 0}
output_data_ports:
    2: !OutputDataPort {data_port_id: 2, data_type: *id001, default_value: 0, name: !!python/unicode 'bottles_output'}
scoped_variables:
    29: !ScopedVariable {data_port_id: 29, data_type: *id001, default_value: 0, name: !!python/unicode 'bottles'}
state_id: !!python/unicode 'GLSUJY'
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: !!python/unicode 'PXTKIH',
        transition_id: 1}
    2: !Transition {from_outcome: 1, from_state: !!python/unicode 'SFZGMH', to_outcome: null,
        to_state: !!python/unicode 'SMCOIB', transition_id: 2}
    6: !Transition {from_outcome: 0, from_state: !!python/unicode 'SMCOIB', to_outcome: 0,
        to_state: !!python/unicode 'GLSUJY', transition_id: 6}
    7: !Transition {from_outcome: 0, from_state: !!python/unicode 'SFZGMH', to_outcome: 0,
        to_state: !!python/unicode 'GLSUJY', transition_id: 7}
    8: !Transition {from_outcome: 0, from_state: !!python/unicode 'PXTKIH', to_outcome: null,
        to_state: !!python/unicode 'NDIVLD', transition_id: 8}
    9: !Transition {from_outcome: 1, from_state: !!python/unicode 'SMCOIB', to_outcome: null,
        to_state: !!python/unicode 'PXTKIH', transition_id: 9}
    10: !Transition {from_outcome: 0, from_state: !!python/unicode 'NDIVLD', to_outcome: null,
        to_state: !!python/unicode 'SFZGMH', transition_id: 10}
