!ExecutionState
filename: script.py
input_data_ports: {}
name: State2
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: /home_local/dark_room/taskcontrol/source/test_scripts/simple_preemption_example/YDPJVU/OQTLKU/PFDNCM
state_id: PFDNCM
