!ExecutionState
description: null
filename: script.py
input_data_ports:
    13: !DataPort {data_port_id: 13, data_type: str, default_value: new_turtle, name: turtle_name}
name: kill_turtle
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: /home_local/brun_sb/develop/taskcontrol/source/test_scripts/turtle_libraries/kill_turtle/KILL_TURTLE
state_id: KILL_TURTLE
