!ExecutionState
filename: script.py
input_data_ports:
    14: !DataPort {data_port_id: 14, data_type: str, default_value: new_turtle, name: turtle_name}
name: kill_turtle
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: KILL_TURTLE
state_id: KILL_TURTLE
state_type: STATE_TYPE.EXECUTION
