!LibraryState
filename: script.py
input_data_ports:
    2: !DataPort {data_port_id: 2, data_type: str, default_value: new_turtle, name: turtle_name}
    3: !DataPort {data_port_id: 3, data_type: float, default_value: 5.0, name: x_pos}
    4: !DataPort {data_port_id: 4, data_type: float, default_value: 5.0, name: y_pos}
    5: !DataPort {data_port_id: 5, data_type: float, default_value: 1.0, name: phi}
library_name: spawn_turtle
library_path: turtle_libraries
name: spawn food 1
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/hungry_turtle_demo/GXTDYN/AAYCDL/KDRRRW
state_id: KDRRRW
state_type: STATE_TYPE.LIBRARY
version: '0.1'
