!ExecutionState
filename: script.py
input_data_ports:
    10: !DataPort {data_port_id: 10, data_type: dict, default_value: null, name: distance
            to user turtle}
name: Move difference
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
path: TIOPDF/DQYWWW/JADXUB/JMVNLG/XUNBRP
state_id: XUNBRP
state_type: STATE_TYPE.EXECUTION
