CONSOLE_DOCKED_POS: 619
CONSOLE_WINDOW_POS: !!python/tuple
- 2217
- 197
CONSOLE_WINDOW_SIZE: !!python/tuple
- 849
- 599
LAST_PATH_OPEN_SAVE: /home/brun_sb/USERSTORE/lru/statemachines/navigation/look backwards
LEFT_BAR_DOCKED_POS: 300
LEFT_BAR_INNER_PANE_POS: 400
LEFT_BAR_WINDOW_POS: !!python/tuple
- 2723
- 264
LEFT_BAR_WINDOW_SIZE: !!python/tuple
- 483
- 670
MAIN_WINDOW_POS: !!python/tuple
- -59
- 0
MAIN_WINDOW_SIZE: !!python/tuple
- 1775
- 988
RIGHT_BAR_DOCKED_POS: 1210
RIGHT_BAR_WINDOW_POS: !!python/tuple
- 2035
- 100
RIGHT_BAR_WINDOW_SIZE: !!python/tuple
- 1604
- 722
SHOW_DATA_FLOWS: true
