!HierarchyState
data_flows: {}
description: null
input_data_ports: {}
name: Inner Activity
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
output_data_ports: {}
scoped_variables: {}
state_id: IFEWBW
transitions:
    8: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: IOICLV,
        transition_id: 8}
    9: !Transition {from_outcome: -2, from_state: IOICLV, to_outcome: null, to_state: YVTDYE,
        transition_id: 9}
    10: !Transition {from_outcome: -2, from_state: YVTDYE, to_outcome: -2, to_state: IFEWBW,
        transition_id: 10}
    11: !Transition {from_outcome: -1, from_state: YVTDYE, to_outcome: -1, to_state: IFEWBW,
        transition_id: 11}
    13: !Transition {from_outcome: -1, from_state: IOICLV, to_outcome: null, to_state: RKHYRL,
        transition_id: 13}
    14: !Transition {from_outcome: -1, from_state: RKHYRL, to_outcome: null, to_state: YVTDYE,
        transition_id: 14}
