!HierarchyState
data_flows: {}
description: null
input_data_ports: {}
name: !!python/unicode 'Inner Activity'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
output_data_ports: {}
scoped_variables: {}
state_id: !!python/unicode 'IFEWBW'
transitions:
    8: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: !!python/unicode 'IOICLV',
        transition_id: 8}
    9: !Transition {from_outcome: -2, from_state: !!python/unicode 'IOICLV', to_outcome: null,
        to_state: !!python/unicode 'YVTDYE', transition_id: 9}
    10: !Transition {from_outcome: -2, from_state: !!python/unicode 'YVTDYE', to_outcome: -2,
        to_state: !!python/unicode 'IFEWBW', transition_id: 10}
    11: !Transition {from_outcome: -1, from_state: !!python/unicode 'YVTDYE', to_outcome: -1,
        to_state: !!python/unicode 'IFEWBW', transition_id: 11}
    13: !Transition {from_outcome: -1, from_state: !!python/unicode 'IOICLV', to_outcome: null,
        to_state: !!python/unicode 'RKHYRL', transition_id: 13}
    14: !Transition {from_outcome: -1, from_state: !!python/unicode 'RKHYRL', to_outcome: null,
        to_state: !!python/unicode 'YVTDYE', transition_id: 14}
