!HierarchyState
data_flows:
    1: !DataFlow {from_key: in1, from_state: OLQBGD, to_key: MyFirstDataInputPort,
        to_state: D5PQTU}
filename: hierarchy_container.py
input_data_ports: {}
name: MyFirstHierarchyState
outcomes:
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: aborted, outcome_id: 1}
    2: !Outcome {name: preempted, outcome_id: 2}
    6: !Outcome {name: Container_Outcome, outcome_id: 6}
output_data_ports: {}
path: ../../test_scripts
scoped_variables: {}
start_state: D5PQTU
state_id: OLQBGD
state_type: STATE_TYPE.HIERARCHY
transitions:
    1: !Transition {from_outcome: 3, from_state: D5PQTU, to_outcome: 6, to_state: null}
