!LibraryState
input_data_port_runtime_values: {6: new_turtle, 7: 1.0, 8: 1.0, 9: 1.0}
library_name: teleport_turtle
library_path: turtle_libraries
name: teleport turtle
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_port_runtime_values: {}
state_id: KQDJYS
use_runtime_value_input_data_ports: {6: true, 7: true, 8: true, 9: true}
use_runtime_value_output_data_ports: {}
version: '0.1'
