!LibraryState
input_data_port_runtime_values: {1: new_ros_node}
library_name: init_ros_node
library_path: ros
name: init ros node
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_port_runtime_values: {}
state_id: CKIWDE
use_runtime_value_input_data_ports: {1: true}
use_runtime_value_output_data_ports: {}
version: '0.1'
