!LibraryState
input_data_ports:
    1: !DataPort {data_port_id: 1, data_type: !!python/name:__builtin__.str '', default_value: new_ros_node,
        name: node_name}
library_name: init_ros_node
library_path: ros
name: init ros node
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
state_id: CKIWDE
version: '0.1'
