!HierarchyState
data_flows:
    7: !DataFlow {data_flow_id: 7, from_key: 3, from_state: AQRXOD, to_key: 5, to_state: LFPQSW}
    8: !DataFlow {data_flow_id: 8, from_key: 4, from_state: AQRXOD, to_key: 6, to_state: LFPQSW}
    10: !DataFlow {data_flow_id: 10, from_key: 9, from_state: LFPQSW, to_key: 3, to_state: JFDYJZ}
    11: !DataFlow {data_flow_id: 11, from_key: 2, from_state: AQRXOD, to_key: 2, to_state: JFDYJZ}
    12: !DataFlow {data_flow_id: 12, from_key: 1, from_state: AQRXOD, to_key: 1, to_state: JFDYJZ}
    14: !DataFlow {data_flow_id: 14, from_key: 4, from_state: JFDYJZ, to_key: 13,
        to_state: RFMJKJ}
description: null
filename: script.py
input_data_ports:
    1: !DataPort {data_port_id: 1, data_type: str, default_value: Please decide wisely,
        name: text}
    2: !DataPort {data_port_id: 2, data_type: str, default_value: You only have this
            one chance, name: subtext}
    3: !DataPort {data_port_id: 3, data_type: str, default_value: Blue pill, name: option
            1}
    4: !DataPort {data_port_id: 4, data_type: str, default_value: Red pill, name: option
            2}
name: Dialog [2 options]
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: option 1, outcome_id: 0}
    1: !Outcome {name: option 2, outcome_id: 1}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/dialog/Dialog [2 options]/AQRXOD
scoped_variables: {}
state_id: AQRXOD
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: LFPQSW,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: LFPQSW, to_outcome: null, to_state: JFDYJZ,
        transition_id: 2}
    3: !Transition {from_outcome: 0, from_state: RFMJKJ, to_outcome: 0, to_state: null,
        transition_id: 3}
    4: !Transition {from_outcome: 1, from_state: RFMJKJ, to_outcome: 1, to_state: null,
        transition_id: 4}
    5: !Transition {from_outcome: 0, from_state: JFDYJZ, to_outcome: null, to_state: RFMJKJ,
        transition_id: 5}
