!HierarchyState
data_flows:
    4: !DataFlow {from_key: 3, from_state: AGNUHU, to_key: 2, to_state: DPAMHS}
filename: script.py
input_data_ports: {}
name: Check for food hierarchy
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports:
    2: !DataPort {data_port_id: 2, data_type: str, default_value: default_turtle_value,
        name: target turtle}
path: TIOPDF/DQYWWW/JADXUB/DPAMHS
scoped_variables: {}
start_state: AGNUHU
state_id: DPAMHS
state_type: STATE_TYPE.HIERARCHY
transitions:
    3: !Transition {from_outcome: 0, from_state: AGNUHU, to_outcome: 0, to_state: null}
    4: !Transition {from_outcome: 1, from_state: AGNUHU, to_outcome: null, to_state: AGNUHU}
