!HierarchyState
data_flows: {}
description: null
input_data_ports: {}
name: h2
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
scoped_variables: {}
state_id: ZDWBKU
transitions:
    5: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: UTRSAA,
        transition_id: 5}
    6: !Transition {from_outcome: 0, from_state: UTRSAA, to_outcome: null, to_state: HADSLI,
        transition_id: 6}
    7: !Transition {from_outcome: 0, from_state: HADSLI, to_outcome: 0, to_state: ZDWBKU,
        transition_id: 7}
