!HierarchyState
data_flows: {}
description: null
input_data_ports: {}
name: test_custom_entry_point
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
scoped_variables: {}
state_id: RWUZOP
transitions:
    2: !Transition {from_outcome: 0, from_state: KAVMZX, to_outcome: 0, to_state: RWUZOP,
        transition_id: 2}
    3: !Transition {from_outcome: 0, from_state: CKGWWI, to_outcome: null, to_state: ZDWBKU,
        transition_id: 3}
    4: !Transition {from_outcome: 0, from_state: ZDWBKU, to_outcome: null, to_state: KAVMZX,
        transition_id: 4}
    8: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: CKGWWI,
        transition_id: 8}
