!ExecutionState
description: null
filename: script.py
input_data_ports:
    2: !DataPort {data_port_id: 2, data_type: !!python/name:__builtin__.int '', default_value: 0,
        name: Bugs}
name: Sing
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: /home_local/buet_ma/DFC/source/test_scripts/tutorials/99_bugs/OTNPAN/GGROCS
state_id: GGROCS
