!ExecutionState
description: null
filename: script.py
input_data_ports:
    3: !DataPort {data_port_id: 3, data_type: &id001 !!python/name:__builtin__.int '',
        default_value: 0, name: Bugs}
name: Process Bugs
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    4: !DataPort {data_port_id: 4, data_type: *id001, default_value: 0, name: Bugs}
path: /home_local/buet_ma/DFC/source/test_scripts/tutorials/99_bugs/OTNPAN/LEUWGC
state_id: LEUWGC
