!ExecutionState
filename: script.py
input_data_ports: {}
name: hierarchy abortion handling
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    2: !DataPort {data_port_id: 2, data_type: str, default_value: null, name: error_check}
path: ../../test_scripts/error_propagation_test/BNXYRR/ZHIMZX
state_id: ZHIMZX
