!ExecutionState
description: null
filename: script.py
input_data_ports: {}
name: Second
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    2: !DataPort {data_port_id: 2, data_type: str, default_value: test_str, name: output2}
    3: !DataPort {data_port_id: 3, data_type: int, default_value: 10, name: output1}
path: ../../test_scripts/barrier_concurrency_test_sm/VFNVDL/AMWCJX/LUDNFV
state_id: LUDNFV
