!BarrierConcurrencyState
data_flows: {}
description: null
filename: script.py
input_data_ports: {}
name: Barrier
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: failure, outcome_id: 1}
output_data_ports: {}
path: /home_local/brun_sb/develop/taskcontrol/source/test_scripts/barrier_concurrency_test_sm/VFNVDL/AMWCJX
scoped_variables: {}
state_id: AMWCJX
transitions:
    2: !Transition {from_outcome: 0, from_state: LUDNFV, to_outcome: null, to_state: unique_decider_sate_id,
        transition_id: 2}
    3: !Transition {from_outcome: 0, from_state: HOSHJH, to_outcome: null, to_state: unique_decider_sate_id,
        transition_id: 3}
    4: !Transition {from_outcome: 0, from_state: unique_decider_sate_id, to_outcome: 0,
        to_state: null, transition_id: 4}
    5: !Transition {from_outcome: 1, from_state: unique_decider_sate_id, to_outcome: 1,
        to_state: null, transition_id: 5}
