!ExecutionState
description: null
filename: script.py
input_data_ports: {}
name: Faulty State
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
path: ../../test_scripts/return_none_test_sm/VZVYGX/ORZCVQ
state_id: ORZCVQ
