!ExecutionState
filename: script.py
input_data_ports: {}
name: create bot turtle
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: Success, outcome_id: 0}
output_data_ports: {}
path: TIOPDF/DQYWWW/RVYPWG
state_id: RVYPWG
state_type: STATE_TYPE.EXECUTION
