!ExecutionState
description: null
input_data_ports:
    30: !InputDataPort {data_port_id: 30, data_type: &id001 !!python/name:__builtin__.int '',
        default_value: null, name: bottles}
name: Decimate bottles
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: done, outcome_id: 0}
output_data_ports:
    31: !OutputDataPort {data_port_id: 31, data_type: *id001, default_value: null,
        name: bottles}
state_id: NDIVLD
