#AUTOCONNECT_TCP_TO_SERVER: false
#AUTOCONNECT_UDP_TO_SERVER: false
CLIENT_UDP_PORT: 7777
SERVER_IP: 127.0.0.1
SERVER_UDP_PORT: 9999
SPACEBOT_CUP_MODE: false
HASH_LENGTH: 8
SALT_LENGTH: 6
MAX_TIME_WAITING_FOR_ACKNOWLEDGEMENTS: 1.0
BURST_NUMBER: 1
TIME_BETWEEN_BURSTS: 0.01
SERVER: true
HISTORY_LENGTH: 1000
ENABLED: true
TYPE: NETWORK_CONFIG