!ExecutionState
description: null
input_data_ports: {}
name: !!python/unicode 'Observer 1'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'success', outcome_id: 0}
output_data_ports: {}
state_id: !!python/unicode 'IONVZR'
