!ExecutionState
description: null
filename: script.py
input_data_ports:
    5: !DataPort {data_port_id: 5, data_type: str, default_value: null, name: option
            1}
    6: !DataPort {data_port_id: 6, data_type: str, default_value: null, name: option
            2}
    16: !DataPort {data_port_id: 16, data_type: str, default_value: null, name: option
            3}
name: Parse options
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    9: !DataPort {data_port_id: 9, data_type: list, default_value: null, name: options}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/dialog/Dialog [3 options]/AQRXOD/LFPQSW
state_id: LFPQSW
