!HierarchyState
data_flows:
    1: !DataFlow {data_flow_id: 1, from_key: 0, from_state: CGJJDO, to_key: 0, to_state: ESGWDP}
description: null
input_data_ports: {}
name: libraray2_for_relocation_test
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    0: !OutputDataPort {data_port_id: 0, data_type: !!python/name:__builtin__.int '',
        default_value: 0, name: out}
scoped_variables: {}
state_id: ESGWDP
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: CGJJDO,
        transition_id: 1}
    2: !Transition {from_outcome: 0, from_state: CGJJDO, to_outcome: 0, to_state: ESGWDP,
        transition_id: 2}
