!HierarchyState
data_flows:
    3: !DataFlow {data_flow_id: 3, from_key: 2, from_state: ZHIMZX, to_key: 1, to_state: BNXYRR}
description: null
input_data_ports: {}
name: error propagation test
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    1: !OutputDataPort {data_port_id: 1, data_type: !!python/name:__builtin__.str '',
        default_value: null, name: error_check}
scoped_variables: {}
state_id: BNXYRR
transitions:
    1: !Transition {from_outcome: null, from_state: null, to_outcome: null, to_state: CLRZWT,
        transition_id: 1}
    2: !Transition {from_outcome: -1, from_state: CLRZWT, to_outcome: null, to_state: ZHIMZX,
        transition_id: 2}
    6: !Transition {from_outcome: 0, from_state: ZHIMZX, to_outcome: 0, to_state: BNXYRR,
        transition_id: 6}
