!ExecutionState
description: null
filename: script.py
input_data_ports:
    4: !DataPort {data_port_id: 4, data_type: str, default_value: null, name: label}
name: Label in list
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports:
    5: !DataPort {data_port_id: 5, data_type: list, default_value: null, name: list}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/dialog/Dialog [Info]/RYDGSS/BMACRG
state_id: BMACRG
