!ExecutionState
description: 'Data exists


    Checks whether the given key exists in the data storage of the next higher library
    or root state.


    Parameters:

    * key: The name of the data


    Outcomes:

    * yes: If key exists

    * no: If key does not exist'
filename: script.py
input_data_ports:
    6: !DataPort {data_port_id: 6, data_type: !!python/name:__builtin__.str '', default_value: null,
        name: key}
name: data exists
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: 'yes', outcome_id: 0}
    1: !Outcome {name: 'no', outcome_id: 1}
output_data_ports: {}
path: /home_local/stei_fn/taskcontrol/source/libraries/generic/storage/data exists/ZJXIKH
state_id: ZJXIKH
