!ExecutionState
description: !!python/unicode 'Data exists


    Checks whether the given key exists in the data storage of the next higher library
    or root state.


    Parameters:

    * key: The name of the data


    Outcomes:

    * yes: If key exists

    * no: If key does not exist'
input_data_ports:
    6: !InputDataPort {data_port_id: 6, data_type: !!python/name:__builtin__.str '',
        default_value: null, name: !!python/unicode 'key'}
name: !!python/unicode 'data exists'
outcomes:
    -2: !Outcome {name: !!python/unicode 'preempted', outcome_id: -2}
    -1: !Outcome {name: !!python/unicode 'aborted', outcome_id: -1}
    0: !Outcome {name: !!python/unicode 'yes', outcome_id: 0}
    1: !Outcome {name: !!python/unicode 'no', outcome_id: 1}
output_data_ports: {}
state_id: !!python/unicode 'ZJXIKH'
