!ExecutionState
description: null
input_data_ports: {}
name: Exit handler
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
    1: !Outcome {name: success2, outcome_id: 1}
output_data_ports: {}
state_id: MEPUNJ
