!LibraryState
input_data_ports:
    13: !DataPort {data_port_id: 13, data_type: !!python/name:__builtin__.str '',
        default_value: new_turtle, name: turtle_name}
library_name: kill_turtle
library_path: turtle_libraries
name: kill turtle
outcomes:
    -2: !Outcome {name: preempted, outcome_id: -2}
    -1: !Outcome {name: aborted, outcome_id: -1}
    0: !Outcome {name: success, outcome_id: 0}
output_data_ports: {}
state_id: HRARIS
version: '0.1'
